version: 2  # Required

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml  # Ensure mkdocs.yml is present

python:
  install:
    - requirements: requirements.txt
