name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - hdf5
  - netcdf4
  - cython
  - numpy
  - pandas
  - matplotlib
  - scipy
  - xarray
  - basemap
  - basemap-data-hires
  - cmocean
  - simplekml
  - requests
  - pip
  - pip:
      - pylatex
      - motuclient
      - copernicusmarine
      - cblind
