site_name: SPASSO documentation
theme:
  name: mkdocs

docs_dir: "."

nav:
  - Home: README.md  # This makes README.md the homepage

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
