site_name: "SPASSO Documentation"
site_url: "https://spasso.readthedocs.io/"
repo_url: "https://github.com/OceanCruises/SPASSO"

theme:
  name: mkdocs

docs_dir: "docs"      # ✅ Store Markdown files here (not ".")
site_dir: "site"      # ✅ Must be outside "docs"

nav:
  - Home: README.md  # Make sure README.md exists in "docs/"

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
